stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    - develop
  script: npm install && npm run build
  artifacts:
    paths:
      - build

deploy-job:
  stage: deploy
  only:
    - develop
  script: cp -vr build/ /var/www/bfcalc
