stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    - develop
  script: npm install && npm run build

deploy-job:
  stage: deploy
  only:
    - develop
  script: cp -vr build/ /home/ubuntu/dev
  # script: cp -vr build/ /var/www/bfcalc
