stages:
  # - build
  - deploy

# build-job:
#   stage: build
#   only:
#     - develop
#   script: npm install 

deploy-job:
  stage: deploy
  only:
    - develop
  script: npm install && npm run build && cp -vr build/ /var/www/bfcalc
